apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
  namespace: aescloud-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-container
        image: aasourav/prometheus:1.15
        ports:
        - containerPort: 8010
